"""Offline tests for the hooker: the generated code and the hook lifecycle.

No client is involved. The target is a ``bytearray``, allocations are handed out
from a fixed base so addresses are predictable, and the generated bytes are
checked directly.

What this proves: the entry patch, the trampoline and the stub are laid out
correctly, they encode the addresses they are given, the lifecycle
(install / enable / disable / receive / remove) behaves, and a failure part-way
through frees what it made.

What it does not prove: that the bytes *execute* the way they are meant to. That
needs a live client and is the first thing the live test must establish.
"""

from __future__ import annotations

import struct
import threading
import time
import unittest

from py4gw.game_thread.hooker import (
    MINIMUM_PATCH,
    STATE_ENABLED_OFFSET,
    STATE_HITS_OFFSET,
    STATE_SIZE,
    Hooker,
    build_entry_patch,
    build_stub,
    build_trampoline,
    stub_size,
)
from py4gw.game_thread.patcher import PAGE_EXECUTE_READ

BASE = 0x00400000
TARGET = 0x00401000
ORIGINAL = bytes.fromhex("55 8B EC 81 EC 00 01 00 00")
BLOCK = 0x10000000
DISPATCH = 0x10001000
ALLOC_BASE = 0x20000000

#: Size of each pretend region in the fake's backing buffer.
REGION = 0x100000

PAGE_READWRITE = 0x04


class FakeTarget:
    """A target with pretend memory, pretend allocations and pretend threads."""

    def __init__(self) -> None:
        # Two separate regions: the target's own memory, and the memory the
        # hooker allocates. They must not overlap, or generated code would
        # overwrite the function being hooked.
        self.memory = bytearray(2 * REGION)
        self.memory[TARGET - BASE : TARGET - BASE + len(ORIGINAL)] = ORIGINAL
        self.allocated: dict[int, int] = {}
        self.freed: list[int] = []
        self.next_allocation = ALLOC_BASE
        self.writes: list[tuple[int, int]] = []
        self.thread_ids = (101,)

    # -- the patcher's needs ----------------------------------------------

    def read(self, address: int, size: int) -> bytes:
        start = self._index(address)
        return bytes(self.memory[start : start + size])

    def write(self, address: int, data: bytes) -> None:
        start = self._index(address)
        self.memory[start : start + len(data)] = data
        self.writes.append((address, len(data)))

    def protect(self, address: int, size: int, protection: int) -> int:
        return PAGE_READWRITE

    def flush_instruction_cache(self, address: int, size: int) -> None:
        pass

    def list_thread_ids(self) -> list[int]:
        return list(self.thread_ids)

    def open_thread(self, thread_id: int) -> int:
        return 0x1000 + thread_id

    def suspend_thread(self, thread_handle: int) -> int:
        return 0

    def resume_thread(self, thread_handle: int) -> int:
        return 0

    def thread_eip(self, thread_handle: int) -> int:
        return BASE + 0x9000

    def close_thread(self, thread_handle: int) -> None:
        pass

    # -- the hooker's needs -----------------------------------------------

    def allocate(self, size: int) -> int:
        address = self.next_allocation
        self.next_allocation += 0x1000
        self.allocated[address] = size
        return address

    def free(self, address: int) -> None:
        self.freed.append(address)

    # -- assertions -------------------------------------------------------

    def at(self, address: int, size: int) -> bytes:
        start = self._index(address)
        return bytes(self.memory[start : start + size])

    def entry(self) -> bytes:
        return self.at(TARGET, len(ORIGINAL))

    def _index(self, address: int) -> int:
        """Map a target address onto the backing buffer.

        The target's own memory occupies the first region and the hooker's
        allocations the second, so the two can never alias.
        """

        if BASE <= address < BASE + REGION:
            return address - BASE
        if ALLOC_BASE <= address < ALLOC_BASE + REGION:
            return REGION + (address - ALLOC_BASE)
        raise ValueError(f"address 0x{address:08X} is outside the fake's regions")


def new_hooker(target: FakeTarget) -> Hooker:
    return Hooker(target, pid=1234, block_address=BLOCK, dispatcher_address=DISPATCH)


class GeneratedCodeTests(unittest.TestCase):
    """The three pieces of code, checked byte by byte."""

    def test_entry_patch_is_a_jump_then_padding(self) -> None:
        patch = build_entry_patch(TARGET, ALLOC_BASE, 9)
        self.assertEqual(len(patch), 9)
        self.assertEqual(patch[0], 0xE9)
        self.assertEqual(patch[5:], b"\x90" * 4)

    def test_entry_patch_jump_lands_on_the_stub(self) -> None:
        patch = build_entry_patch(TARGET, ALLOC_BASE, 9)
        offset = struct.unpack("<I", patch[1:5])[0]
        # The displacement is measured from the end of the jump instruction.
        self.assertEqual((TARGET + 5 + offset) & 0xFFFFFFFF, ALLOC_BASE)

    def test_entry_patch_needs_room_for_a_jump(self) -> None:
        with self.assertRaises(ValueError):
            build_entry_patch(TARGET, ALLOC_BASE, MINIMUM_PATCH - 1)

    def test_trampoline_replays_the_displaced_bytes(self) -> None:
        trampoline = build_trampoline(ALLOC_BASE, ORIGINAL, TARGET + 9)
        self.assertEqual(trampoline[:9], ORIGINAL)
        self.assertEqual(trampoline[9], 0xE9)
        offset = struct.unpack("<I", trampoline[10:14])[0]
        self.assertEqual((ALLOC_BASE + 14 + offset) & 0xFFFFFFFF, TARGET + 9)

    def test_trampoline_needs_displaced_bytes(self) -> None:
        with self.assertRaises(ValueError):
            build_trampoline(ALLOC_BASE, b"", TARGET)

    def test_stub_saves_and_restores_everything(self) -> None:
        stub = build_stub(ALLOC_BASE, 0x20000000, BLOCK, DISPATCH, 0x20001000)
        self.assertEqual(stub[0], 0x9C)  # pushfd
        self.assertEqual(stub[1], 0x60)  # pushad
        self.assertIn(b"\x61\x9d", stub)  # popad, popfd

    def test_stub_calls_the_dispatcher_with_the_block(self) -> None:
        stub = build_stub(ALLOC_BASE, 0x20000000, BLOCK, DISPATCH, 0x20001000)
        self.assertIn(struct.pack("<I", BLOCK), stub)
        self.assertIn(struct.pack("<I", DISPATCH), stub)
        # push <block>; mov eax, <dispatcher>; call eax
        self.assertIn(
            bytes((0x68,)) + struct.pack("<I", BLOCK)
            + bytes((0xB8,)) + struct.pack("<I", DISPATCH)
            + bytes((0xFF, 0xD0)),
            stub,
        )

    def test_stub_does_not_clean_the_stack_after_the_call(self) -> None:
        """The dispatcher is __stdcall and pops its own argument."""

        stub = build_stub(ALLOC_BASE, 0x20000000, BLOCK, DISPATCH, 0x20001000)
        call_at = stub.index(bytes((0xFF, 0xD0)))
        self.assertNotEqual(stub[call_at + 2 : call_at + 5], bytes((0x83, 0xC4, 0x04)))

    def test_stub_jumps_to_the_trampoline(self) -> None:
        trampoline = 0x20001000
        stub = build_stub(ALLOC_BASE, 0x20000000, BLOCK, DISPATCH, trampoline)
        jump_at = stub.rindex(0xE9)
        offset = struct.unpack("<I", stub[jump_at + 1 : jump_at + 5])[0]
        self.assertEqual((ALLOC_BASE + jump_at + 5 + offset) & 0xFFFFFFFF, trampoline)

    def test_stub_skip_branch_lands_after_the_call(self) -> None:
        stub = build_stub(ALLOC_BASE, 0x20000000, BLOCK, DISPATCH, 0x20001000)
        jump_at = stub.index(0x74)
        # The skip target is the popad; the dispatcher call must sit between.
        self.assertEqual(stub[jump_at + 2 + stub[jump_at + 1]], 0x61)

    def test_stub_reads_the_enabled_word_and_counts_hits(self) -> None:
        state = 0x20000000
        stub = build_stub(ALLOC_BASE, state, BLOCK, DISPATCH, 0x20001000)
        self.assertIn(bytes((0xB8,)) + struct.pack("<I", state), stub)
        self.assertIn(bytes((0xFF, 0x40, 0x04)), stub)  # inc dword [eax+4]
        self.assertIn(bytes((0x83, 0x38, 0x00)), stub)  # cmp dword [eax], 0

    def test_stub_size_is_independent_of_addresses(self) -> None:
        self.assertEqual(stub_size(), len(build_stub(1, 2, 3, 4, 5)))
        self.assertEqual(stub_size(), len(build_stub(9, 9, 9, 9, 9)))

    def test_relative_offsets_wrap_across_two_gigabytes(self) -> None:
        """A displacement is a signed 32-bit number, not a Python integer."""

        patch = build_entry_patch(0x10000000, 0xF0000000, 5)
        offset = struct.unpack("<I", patch[1:5])[0]
        self.assertEqual((0x10000000 + 5 + offset) & 0xFFFFFFFF, 0xF0000000)


class InstallTests(unittest.TestCase):
    """What install writes, and what it refuses."""

    def test_install_patches_the_target_and_installs(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        self.assertEqual(hooker.installed, ("entry",))
        self.assertEqual(target.entry()[0], 0xE9)
        self.assertEqual(target.entry()[5:], b"\x90" * 4)

    def test_install_allocates_state_trampoline_and_stub(self) -> None:
        target = FakeTarget()
        new_hooker(target).install("entry", TARGET, ORIGINAL)

        sizes = list(target.allocated.values())
        self.assertEqual(len(sizes), 3)
        self.assertIn(STATE_SIZE, sizes)
        self.assertIn(stub_size(), sizes)
        self.assertIn(len(ORIGINAL) + MINIMUM_PATCH, sizes)

    def test_the_trampoline_replays_the_original_bytes(self) -> None:
        """Without this the client's function would lose its prologue."""

        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        # The second allocation is the trampoline.
        trampoline = sorted(target.allocated)[1]
        self.assertEqual(target.at(trampoline, len(ORIGINAL)), ORIGINAL)

    def test_the_entry_patch_jumps_to_the_stub(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        stub = sorted(target.allocated)[2]
        offset = struct.unpack("<I", target.entry()[1:5])[0]
        self.assertEqual((TARGET + 5 + offset) & 0xFFFFFFFF, stub)

    def test_the_stub_points_at_the_shared_block(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        stub = sorted(target.allocated)[2]
        body = target.at(stub, stub_size())
        self.assertIn(struct.pack("<I", BLOCK), body)
        self.assertIn(struct.pack("<I", DISPATCH), body)

    def test_generated_code_is_left_executable_and_not_writable(self) -> None:
        target = FakeTarget()
        writes: list[tuple[int, int]] = []
        original_protect = target.protect

        def recording_protect(address: int, size: int, protection: int) -> int:
            writes.append((address, protection))
            return original_protect(address, size, protection)

        target.protect = recording_protect  # type: ignore[method-assign]
        new_hooker(target).install("entry", TARGET, ORIGINAL)

        protections = [protection for _, protection in writes]
        self.assertEqual(protections.count(PAGE_EXECUTE_READ), 2)

    def test_install_starts_enabled(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        state = sorted(target.allocated)[0]
        self.assertEqual(target.at(state, 4), struct.pack("<I", 1))

    def test_install_refuses_a_stale_declaration(self) -> None:
        target = FakeTarget()
        target.memory[TARGET - BASE] = 0x90

        with self.assertRaises(RuntimeError):
            new_hooker(target).install("entry", TARGET, ORIGINAL)
        self.assertEqual(target.entry(), b"\x90" + ORIGINAL[1:])

    def test_a_failed_install_frees_what_it_made(self) -> None:
        """The entry patch is last, so nothing can be inside the stub on failure."""

        target = FakeTarget()
        target.memory[TARGET - BASE] = 0x90

        with self.assertRaises(RuntimeError):
            new_hooker(target).install("entry", TARGET, ORIGINAL)

        self.assertEqual(sorted(target.freed), sorted(target.allocated))
        self.assertEqual(target.entry(), b"\x90" + ORIGINAL[1:])

    def test_install_arguments_are_validated(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)

        with self.assertRaises(ValueError):
            hooker.install("", TARGET, ORIGINAL)
        with self.assertRaises(ValueError):
            hooker.install("short", TARGET, ORIGINAL[:4])
        with self.assertRaises(ValueError):
            hooker.install("bad", 0, ORIGINAL)

    def test_a_duplicate_name_is_refused(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        with self.assertRaises(ValueError):
            hooker.install("entry", TARGET, ORIGINAL)

    def test_hooker_arguments_are_validated(self) -> None:
        target = FakeTarget()
        with self.assertRaises(ValueError):
            Hooker(target, pid=1234, block_address=0, dispatcher_address=DISPATCH)
        with self.assertRaises(ValueError):
            Hooker(target, pid=1234, block_address=BLOCK, dispatcher_address=0)


class LifecycleTests(unittest.TestCase):
    """Enable, disable, count, remove."""

    def test_disable_and_enable_write_the_enabled_word_only(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        state = sorted(target.allocated)[0]

        hooker.disable("entry")
        self.assertEqual(target.at(state, 4), struct.pack("<I", 0))
        self.assertEqual(target.entry()[0], 0xE9)  # still patched

        hooker.enable("entry")
        self.assertEqual(target.at(state, 4), struct.pack("<I", 1))

    def test_the_state_offsets_are_where_the_stub_expects_them(self) -> None:
        self.assertEqual(STATE_ENABLED_OFFSET, 0)
        self.assertEqual(STATE_HITS_OFFSET, 4)
        self.assertEqual(STATE_SIZE, 16)

    def test_hits_reads_the_counter(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        state = sorted(target.allocated)[0]

        self.assertEqual(hooker.hits("entry"), 0)
        target.write(state + STATE_HITS_OFFSET, struct.pack("<I", 42))
        self.assertEqual(hooker.hits("entry"), 42)

    def test_wait_for_hits_returns_once_the_counter_moves(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        state = sorted(target.allocated)[0]

        def fire() -> None:
            time.sleep(0.02)
            target.write(state + STATE_HITS_OFFSET, struct.pack("<I", 3))

        worker = threading.Thread(target=fire)
        worker.start()
        self.addCleanup(worker.join)

        self.assertEqual(
            hooker.wait_for_hits("entry", minimum_delta=1, timeout_ms=2000), 3
        )

    def test_wait_for_hits_times_out_when_the_function_never_runs(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        with self.assertRaises(TimeoutError) as caught:
            hooker.wait_for_hits("entry", minimum_delta=2, timeout_ms=30)

        message = str(caught.exception)
        self.assertIn("entry", message)
        self.assertIn("2 were needed", message)

    def test_wait_for_hits_wants_a_positive_delta(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        with self.assertRaises(ValueError):
            hooker.wait_for_hits("entry", minimum_delta=0)

    def test_remove_restores_the_original_bytes(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        hooker.remove("entry")

        self.assertEqual(target.entry(), ORIGINAL)
        self.assertEqual(hooker.installed, ())

    def test_remove_leaves_the_generated_code_mapped(self) -> None:
        """A thread may be inside the stub; freeing it would be fatal."""

        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        hooker.remove("entry")

        self.assertEqual(target.freed, [])

    def test_remove_disables_before_restoring(self) -> None:
        """Anything entering between the two steps must do nothing."""

        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        state = sorted(target.allocated)[0]

        hooker.remove("entry")
        self.assertEqual(target.at(state, 4), struct.pack("<I", 0))

    def test_remove_all_removes_everything(self) -> None:
        target = FakeTarget()
        second = TARGET + 0x200
        target.memory[second - BASE : second - BASE + len(ORIGINAL)] = ORIGINAL
        hooker = new_hooker(target)
        hooker.install("first", TARGET, ORIGINAL)
        hooker.install("second", second, ORIGINAL)

        hooker.remove_all()
        self.assertEqual(hooker.installed, ())
        self.assertEqual(target.entry(), ORIGINAL)

    def test_unknown_names_are_refused(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        for call in (
            lambda: hooker.enable("missing"),
            lambda: hooker.disable("missing"),
            lambda: hooker.hits("missing"),
            lambda: hooker.remove("missing"),
        ):
            with self.assertRaises(ValueError):
                call()


if __name__ == "__main__":
    unittest.main(verbosity=2)
