"""Offline tests for the hooker: the generated code and the hook lifecycle.

No client is involved. The target is a ``bytearray``, allocations are handed out
from a fixed base so addresses are predictable, and the generated bytes are
checked directly.

What this proves: the entry patch, the trampoline and the stub are laid out
correctly, they encode the addresses they are given, the lifecycle
(install / enable / disable / receive / remove) behaves, and a failure part-way
through frees what it made.

What it also proves, for the **post-call form**: that its stub executes. That form
swaps the hooked function's return address, so its stack discipline cannot be
checked by reading bytes — ``PostCallExecutionTests`` therefore allocates real
executable memory, patches a synthetic function with the real entry patch, calls it
through ``ctypes`` and measures: the payload runs after the body, the return value
and the stack are where the caller left them, a re-entrant payload nests, and a
disabled hook or a full frame stack passes the call through untouched.

What it does not prove: that the *entry* form executes the way it is meant to
against a real client. That needs a live client and is the first thing the live
test must establish.
"""

from __future__ import annotations

import ctypes
import struct
import threading
import time
import unittest
from ctypes import wintypes

from py4gw.game_thread.hooker import (
    MINIMUM_PATCH,
    POST_DEPTH,
    POST_DEPTH_OFFSET,
    POST_SLOTS_OFFSET,
    STATE_ENABLED_OFFSET,
    STATE_HITS_OFFSET,
    STUB_HEAD_SIZE,
    STUB_PROLOGUE,
    STATE_INFLIGHT_OFFSET,
    STATE_SIZE,
    Hooker,
    build_entry_patch,
    build_stub,
    build_trampoline,
    is_generated_stub,
    is_relative_jump,
    post_frame_size,
    post_state_size,
    stub_size,
)
from py4gw.game_thread.patcher import PAGE_EXECUTE_READ

BASE = 0x00400000
TARGET = 0x00401000
ORIGINAL = bytes.fromhex("55 8B EC 81 EC 00 01 00 00")
BLOCK = 0x10000000
DISPATCH = 0x10001000
ALLOC_BASE = 0x20000000

#: Size of each pretend region in the fake's backing buffer.
REGION = 0x100000

PAGE_READWRITE = 0x04

#: ``kernel32``'s allocator, for the tests that run generated code in this process.
kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
kernel32.VirtualAlloc.restype = ctypes.c_void_p
kernel32.VirtualAlloc.argtypes = (
    ctypes.c_void_p,
    ctypes.c_size_t,
    wintypes.DWORD,
    wintypes.DWORD,
)
kernel32.VirtualFree.argtypes = (ctypes.c_void_p, ctypes.c_size_t, wintypes.DWORD)

MEM_COMMIT_RESERVE = 0x1000 | 0x2000
MEM_RELEASE = 0x8000
PAGE_EXECUTE_READWRITE = 0x40

#: How many of the hooked function's arguments the post-call rig forwards, which is what the
#: observer hook forwards: the message id and its packet.
FORWARDED = 2

#: The packet pointer the rig's payload is handed, standing in for the shared block.
RIG_BLOCK = 0x0DEADBEE


class FakeTarget:
    """A target with pretend memory, pretend allocations and pretend threads."""

    def __init__(self) -> None:
        # Two separate regions: the target's own memory, and the memory the
        # hooker allocates. They must not overlap, or generated code would
        # overwrite the function being hooked.
        self.memory = bytearray(2 * REGION)
        self.memory[TARGET - BASE : TARGET - BASE + len(ORIGINAL)] = ORIGINAL
        self.allocated: dict[int, int] = {}
        self.freed: list[int] = []
        self.next_allocation = ALLOC_BASE
        self.writes: list[tuple[int, int]] = []
        self.thread_ids = (101,)

    # -- the patcher's needs ----------------------------------------------

    def read(self, address: int, size: int) -> bytes:
        start = self._index(address)
        return bytes(self.memory[start : start + size])

    def write(self, address: int, data: bytes) -> None:
        start = self._index(address)
        self.memory[start : start + len(data)] = data
        self.writes.append((address, len(data)))

    def protect(self, address: int, size: int, protection: int) -> int:
        return PAGE_READWRITE

    def flush_instruction_cache(self, address: int, size: int) -> None:
        pass

    def list_thread_ids(self) -> list[int]:
        return list(self.thread_ids)

    def open_thread(self, thread_id: int) -> int:
        return 0x1000 + thread_id

    def suspend_thread(self, thread_handle: int) -> int:
        return 0

    def resume_thread(self, thread_handle: int) -> int:
        return 0

    def thread_eip(self, thread_handle: int) -> int:
        return BASE + 0x9000

    def close_thread(self, thread_handle: int) -> None:
        pass

    # -- the hooker's needs -----------------------------------------------

    def allocate(self, size: int) -> int:
        address = self.next_allocation
        self.next_allocation += 0x1000
        self.allocated[address] = size
        return address

    def free(self, address: int) -> None:
        self.freed.append(address)

    # -- assertions -------------------------------------------------------

    def at(self, address: int, size: int) -> bytes:
        start = self._index(address)
        return bytes(self.memory[start : start + size])

    def entry(self) -> bytes:
        return self.at(TARGET, len(ORIGINAL))

    def _index(self, address: int) -> int:
        """Map a target address onto the backing buffer.

        The target's own memory occupies the first region and the hooker's
        allocations the second, so the two can never alias.
        """

        if BASE <= address < BASE + REGION:
            return address - BASE
        if ALLOC_BASE <= address < ALLOC_BASE + REGION:
            return REGION + (address - ALLOC_BASE)
        raise ValueError(f"address 0x{address:08X} is outside the fake's regions")


def new_hooker(target: FakeTarget) -> Hooker:
    return Hooker(target, pid=1234, block_address=BLOCK, dispatcher_address=DISPATCH)


class GeneratedCodeTests(unittest.TestCase):
    """The three pieces of code, checked byte by byte."""

    def test_entry_patch_is_a_jump_then_padding(self) -> None:
        patch = build_entry_patch(TARGET, ALLOC_BASE, 9)
        self.assertEqual(len(patch), 9)
        self.assertEqual(patch[0], 0xE9)
        self.assertEqual(patch[5:], b"\x90" * 4)

    def test_entry_patch_jump_lands_on_the_stub(self) -> None:
        patch = build_entry_patch(TARGET, ALLOC_BASE, 9)
        offset = struct.unpack("<I", patch[1:5])[0]
        # The displacement is measured from the end of the jump instruction.
        self.assertEqual((TARGET + 5 + offset) & 0xFFFFFFFF, ALLOC_BASE)

    def test_entry_patch_needs_room_for_a_jump(self) -> None:
        with self.assertRaises(ValueError):
            build_entry_patch(TARGET, ALLOC_BASE, MINIMUM_PATCH - 1)

    def test_trampoline_replays_the_displaced_bytes(self) -> None:
        trampoline = build_trampoline(ALLOC_BASE, ORIGINAL, TARGET + 9)
        self.assertEqual(trampoline[:9], ORIGINAL)
        self.assertEqual(trampoline[9], 0xE9)
        offset = struct.unpack("<I", trampoline[10:14])[0]
        self.assertEqual((ALLOC_BASE + 14 + offset) & 0xFFFFFFFF, TARGET + 9)

    def test_trampoline_needs_displaced_bytes(self) -> None:
        with self.assertRaises(ValueError):
            build_trampoline(ALLOC_BASE, b"", TARGET)

    def test_stub_saves_and_restores_everything(self) -> None:
        stub = build_stub(ALLOC_BASE, 0x20000000, BLOCK, DISPATCH, 0x20001000)
        self.assertEqual(stub[0], 0x9C)  # pushfd
        self.assertEqual(stub[1], 0x60)  # pushad
        self.assertIn(b"\x61\x9d", stub)  # popad, popfd

    def test_stub_calls_the_dispatcher_with_the_block(self) -> None:
        stub = build_stub(ALLOC_BASE, 0x20000000, BLOCK, DISPATCH, 0x20001000)
        self.assertIn(struct.pack("<I", BLOCK), stub)
        self.assertIn(struct.pack("<I", DISPATCH), stub)
        # push <block>; mov eax, <dispatcher>; call eax
        self.assertIn(
            bytes((0x68,)) + struct.pack("<I", BLOCK)
            + bytes((0xB8,)) + struct.pack("<I", DISPATCH)
            + bytes((0xFF, 0xD0)),
            stub,
        )

    def test_stub_does_not_clean_the_stack_after_the_call(self) -> None:
        """The dispatcher is __stdcall and pops its own argument."""

        stub = build_stub(ALLOC_BASE, 0x20000000, BLOCK, DISPATCH, 0x20001000)
        call_at = stub.index(bytes((0xFF, 0xD0)))
        self.assertNotEqual(stub[call_at + 2 : call_at + 5], bytes((0x83, 0xC4, 0x04)))

    def test_stub_jumps_to_the_trampoline(self) -> None:
        trampoline = 0x20001000
        stub = build_stub(ALLOC_BASE, 0x20000000, BLOCK, DISPATCH, trampoline)
        jump_at = stub.rindex(0xE9)
        offset = struct.unpack("<I", stub[jump_at + 1 : jump_at + 5])[0]
        self.assertEqual((ALLOC_BASE + jump_at + 5 + offset) & 0xFFFFFFFF, trampoline)

    def test_stub_skip_branch_lands_after_the_call(self) -> None:
        stub = build_stub(ALLOC_BASE, 0x20000000, BLOCK, DISPATCH, 0x20001000)
        jump_at = stub.index(0x74)
        # The skip target is the popad; the dispatcher call must sit between.
        self.assertEqual(stub[jump_at + 2 + stub[jump_at + 1]], 0x61)

    def test_stub_reads_the_enabled_word_and_counts_hits(self) -> None:
        state = 0x20000000
        stub = build_stub(ALLOC_BASE, state, BLOCK, DISPATCH, 0x20001000)
        self.assertIn(bytes((0xB8,)) + struct.pack("<I", state), stub)
        self.assertIn(bytes((0xFF, 0x40, 0x04)), stub)  # inc dword [eax+4]
        self.assertIn(bytes((0x83, 0x38, 0x00)), stub)  # cmp dword [eax], 0

    def test_stub_size_is_independent_of_addresses(self) -> None:
        self.assertEqual(stub_size(), len(build_stub(1, 2, 3, 4, 5)))
        self.assertEqual(stub_size(), len(build_stub(9, 9, 9, 9, 9)))

    def test_relative_offsets_wrap_across_two_gigabytes(self) -> None:
        """A displacement is a signed 32-bit number, not a Python integer."""

        patch = build_entry_patch(0x10000000, 0xF0000000, 5)
        offset = struct.unpack("<I", patch[1:5])[0]
        self.assertEqual((0x10000000 + 5 + offset) & 0xFFFFFFFF, 0xF0000000)


class InstallTests(unittest.TestCase):
    """What install writes, and what it refuses."""

    def test_install_patches_the_target_and_installs(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        self.assertEqual(hooker.installed, ("entry",))
        self.assertEqual(target.entry()[0], 0xE9)
        self.assertEqual(target.entry()[5:], b"\x90" * 4)

    def test_install_allocates_state_trampoline_and_stub(self) -> None:
        target = FakeTarget()
        new_hooker(target).install("entry", TARGET, ORIGINAL)

        sizes = list(target.allocated.values())
        self.assertEqual(len(sizes), 3)
        self.assertIn(STATE_SIZE, sizes)
        self.assertIn(stub_size(), sizes)
        self.assertIn(len(ORIGINAL) + MINIMUM_PATCH, sizes)

    def test_the_trampoline_replays_the_original_bytes(self) -> None:
        """Without this the client's function would lose its prologue."""

        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        # The second allocation is the trampoline.
        trampoline = sorted(target.allocated)[1]
        self.assertEqual(target.at(trampoline, len(ORIGINAL)), ORIGINAL)

    def test_the_entry_patch_jumps_to_the_stub(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        stub = sorted(target.allocated)[2]
        offset = struct.unpack("<I", target.entry()[1:5])[0]
        self.assertEqual((TARGET + 5 + offset) & 0xFFFFFFFF, stub)

    def test_the_stub_points_at_the_shared_block(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        stub = sorted(target.allocated)[2]
        body = target.at(stub, stub_size())
        self.assertIn(struct.pack("<I", BLOCK), body)
        self.assertIn(struct.pack("<I", DISPATCH), body)

    def test_generated_code_is_left_executable_and_not_writable(self) -> None:
        target = FakeTarget()
        writes: list[tuple[int, int]] = []
        original_protect = target.protect

        def recording_protect(address: int, size: int, protection: int) -> int:
            writes.append((address, protection))
            return original_protect(address, size, protection)

        target.protect = recording_protect  # type: ignore[method-assign]
        new_hooker(target).install("entry", TARGET, ORIGINAL)

        protections = [protection for _, protection in writes]
        self.assertEqual(protections.count(PAGE_EXECUTE_READ), 2)

    def test_install_starts_enabled(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        state = sorted(target.allocated)[0]
        self.assertEqual(target.at(state, 4), struct.pack("<I", 1))

    def test_install_refuses_a_stale_declaration(self) -> None:
        target = FakeTarget()
        target.memory[TARGET - BASE] = 0x90

        with self.assertRaises(RuntimeError):
            new_hooker(target).install("entry", TARGET, ORIGINAL)
        self.assertEqual(target.entry(), b"\x90" + ORIGINAL[1:])

    def test_a_failed_install_frees_what_it_made(self) -> None:
        """The entry patch is last, so nothing can be inside the stub on failure."""

        target = FakeTarget()
        target.memory[TARGET - BASE] = 0x90

        with self.assertRaises(RuntimeError):
            new_hooker(target).install("entry", TARGET, ORIGINAL)

        self.assertEqual(sorted(target.freed), sorted(target.allocated))
        self.assertEqual(target.entry(), b"\x90" + ORIGINAL[1:])

    def test_install_arguments_are_validated(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)

        with self.assertRaises(ValueError):
            hooker.install("", TARGET, ORIGINAL)
        with self.assertRaises(ValueError):
            hooker.install("short", TARGET, ORIGINAL[:4])
        with self.assertRaises(ValueError):
            hooker.install("bad", 0, ORIGINAL)

    def test_a_duplicate_name_is_refused(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        with self.assertRaises(ValueError):
            hooker.install("entry", TARGET, ORIGINAL)

    def test_hooker_arguments_are_validated(self) -> None:
        target = FakeTarget()
        with self.assertRaises(ValueError):
            Hooker(target, pid=1234, block_address=0, dispatcher_address=DISPATCH)
        with self.assertRaises(ValueError):
            Hooker(target, pid=1234, block_address=BLOCK, dispatcher_address=0)


class LifecycleTests(unittest.TestCase):
    """Enable, disable, count, remove."""

    def test_disable_and_enable_write_the_enabled_word_only(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        state = sorted(target.allocated)[0]

        hooker.disable("entry")
        self.assertEqual(target.at(state, 4), struct.pack("<I", 0))
        self.assertEqual(target.entry()[0], 0xE9)  # still patched

        hooker.enable("entry")
        self.assertEqual(target.at(state, 4), struct.pack("<I", 1))

    def test_the_state_offsets_are_where_the_stub_expects_them(self) -> None:
        self.assertEqual(STATE_ENABLED_OFFSET, 0)
        self.assertEqual(STATE_HITS_OFFSET, 4)
        self.assertEqual(STATE_SIZE, 16)

    def test_hits_reads_the_counter(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        state = sorted(target.allocated)[0]

        self.assertEqual(hooker.hits("entry"), 0)
        target.write(state + STATE_HITS_OFFSET, struct.pack("<I", 42))
        self.assertEqual(hooker.hits("entry"), 42)

    def test_wait_for_hits_returns_once_the_counter_moves(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        state = sorted(target.allocated)[0]

        def fire() -> None:
            time.sleep(0.02)
            target.write(state + STATE_HITS_OFFSET, struct.pack("<I", 3))

        worker = threading.Thread(target=fire)
        worker.start()
        self.addCleanup(worker.join)

        self.assertEqual(
            hooker.wait_for_hits("entry", minimum_delta=1, timeout_ms=2000), 3
        )

    def test_wait_for_hits_times_out_when_the_function_never_runs(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        with self.assertRaises(TimeoutError) as caught:
            hooker.wait_for_hits("entry", minimum_delta=2, timeout_ms=30)

        message = str(caught.exception)
        self.assertIn("entry", message)
        self.assertIn("2 were needed", message)

    def test_wait_for_hits_wants_a_positive_delta(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        with self.assertRaises(ValueError):
            hooker.wait_for_hits("entry", minimum_delta=0)

    def test_remove_restores_the_original_bytes(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        hooker.remove("entry")

        self.assertEqual(target.entry(), ORIGINAL)
        self.assertEqual(hooker.installed, ())

    def test_remove_leaves_the_generated_code_mapped(self) -> None:
        """A thread may be inside the stub; freeing it would be fatal."""

        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        hooker.remove("entry")

        self.assertEqual(target.freed, [])

    def test_remove_disables_before_restoring(self) -> None:
        """Anything entering between the two steps must do nothing."""

        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        state = sorted(target.allocated)[0]

        hooker.remove("entry")
        self.assertEqual(target.at(state, 4), struct.pack("<I", 0))

    def test_remove_all_removes_everything(self) -> None:
        target = FakeTarget()
        second = TARGET + 0x200
        target.memory[second - BASE : second - BASE + len(ORIGINAL)] = ORIGINAL
        hooker = new_hooker(target)
        hooker.install("first", TARGET, ORIGINAL)
        hooker.install("second", second, ORIGINAL)

        hooker.remove_all()
        self.assertEqual(hooker.installed, ())
        self.assertEqual(target.entry(), ORIGINAL)

    def test_unknown_names_are_refused(self) -> None:
        target = FakeTarget()
        hooker = new_hooker(target)
        for call in (
            lambda: hooker.enable("missing"),
            lambda: hooker.disable("missing"),
            lambda: hooker.hits("missing"),
            lambda: hooker.remove("missing"),
        ):
            with self.assertRaises(ValueError):
                call()


class PostCallStubTests(unittest.TestCase):
    """The post-call form's shape, read off the bytes it generates."""

    def test_the_stub_size_is_independent_of_addresses(self) -> None:
        self.assertEqual(
            stub_size(FORWARDED, True),
            len(build_stub(1, 2, 3, 4, 5, FORWARDED, True)),
        )
        self.assertEqual(
            stub_size(FORWARDED, True),
            len(build_stub(9, 9, 9, 9, 9, FORWARDED, True)),
        )

    def test_the_post_call_form_is_longer_than_the_entry_form(self) -> None:
        """It keeps a frame and runs the payload on the way out, so it has more to do."""

        self.assertGreater(stub_size(FORWARDED, True), stub_size(FORWARDED, False))

    def test_a_frame_holds_the_return_address_and_the_arguments(self) -> None:
        self.assertEqual(post_frame_size(0), 4)
        self.assertEqual(post_frame_size(2), 12)
        self.assertEqual(post_frame_size(3), 16)

    def test_the_state_keeps_one_frame_per_level(self) -> None:
        """A re-entrant call nests, so the depth is a stack and not a single slot."""

        self.assertEqual(
            post_state_size(FORWARDED),
            POST_SLOTS_OFFSET + POST_DEPTH * post_frame_size(FORWARDED),
        )
        self.assertEqual(
            post_state_size(FORWARDED) - post_state_size(0),
            POST_DEPTH * 4 * FORWARDED,
            "every level keeps its own copy of the arguments",
        )
        self.assertGreater(post_state_size(FORWARDED), STATE_SIZE)

    def test_the_depth_word_is_outside_the_words_the_plain_form_uses(self) -> None:
        """The two forms share ``enabled`` and ``hits``, so a lifecycle read still works."""

        self.assertEqual(STATE_ENABLED_OFFSET, 0)
        self.assertEqual(STATE_HITS_OFFSET, 4)
        self.assertGreaterEqual(POST_DEPTH_OFFSET, STATE_SIZE)

    def test_a_negative_argument_count_is_refused(self) -> None:
        with self.assertRaises(ValueError):
            build_stub(1, 2, 3, 4, 5, -1, True)


class InFlightTests(unittest.TestCase):
    """The in-flight count: what makes freeing generated code safe, proved by running the code.

    A byte-level check would be satisfied by a stub that incremented and decremented the wrong register or the
    wrong offset, and the client would crash the first time it was removed. So the count is driven here: the
    stub is executed in real executable memory by `_PostCallRig`, and the payload reads the count **while it
    is inside** it. Native keeps the same number, for the same reason, across its own render hook
    (`++g_active_render_hooks` on entry, `--` on exit, `render.cpp:75-111`), and waits for it at shutdown
    (`:61-73`).
    """

    def test_the_count_is_one_while_the_stub_holds_a_call(self) -> None:
        rig = _PostCallRig()
        self.addCleanup(rig.close)
        seen: list[int] = []

        def payload(*arguments: object) -> None:
            seen.append(rig.in_flight())

        rig.set_payload(payload)
        self.assertEqual(rig.in_flight(), 0, "nothing is inside before the call")

        result = rig.call(1, 2)

        self.assertEqual(result, _PostCallRig.RESULT, "the client's own return value is untouched")
        self.assertEqual(rig.marker_value(), _PostCallRig.MARKER, "and its body still ran")
        self.assertEqual(seen, [1], "the payload runs with its own call counted")
        self.assertEqual(rig.in_flight(), 0, "and an outer thread sees an empty stub again")

    def test_a_disabled_hook_is_never_counted(self) -> None:
        """The count starts after the enabled check, so a pass-through cannot make a removal wait."""

        rig = _PostCallRig()
        self.addCleanup(rig.close)
        rig.set_payload(None)          # a payload address of zero: calling it would crash the test
        rig.set_enabled(0)

        result = rig.call(1, 2)

        self.assertEqual(result, _PostCallRig.RESULT)
        self.assertEqual(rig.in_flight(), 0)

    def test_the_count_is_reported_and_nothing_is_freed_when_it_does_not_drain(self) -> None:
        """A call still inside is **reported**, not slept off: freeing under it is how a client dies."""

        from unittest import mock

        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        state = sorted(target.allocated)[0]
        target.write(state + STATE_INFLIGHT_OFFSET, struct.pack("<I", 3))

        with mock.patch("py4gw.game_thread.hooker.FREE_WAIT_SECONDS", 0.02):
            with self.assertRaises(RuntimeError) as caught:
                hooker.remove("entry", free_code=True)

        self.assertIn("inside its stub", str(caught.exception))
        self.assertIn("Nothing was freed", str(caught.exception))
        self.assertEqual(target.freed, [], "no allocation is freed while a call is inside")
        self.assertEqual(target.entry(), ORIGINAL, "but the entry itself is restored")

    def test_an_empty_stub_frees_its_code_and_keeps_the_trampoline(self) -> None:
        """The trampoline is the one piece the count cannot cover, so it is never freed."""

        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        self.assertEqual(len(target.allocated), 3, "state, trampoline and stub")

        hooker.remove("entry", free_code=True)

        self.assertEqual(len(target.freed), 2, "the stub and the state; the trampoline stays mapped")


class ChainedEntryTests(unittest.TestCase):
    """Sitting on top of another runtime's entry jump: the arrangement that happens in practice.

    Reforged is injected before this library, so the entry of each shared function already carries its
    five-byte ``jmp rel32`` when this library connects (MinHook's own shape, ``hook.c:355``). Hooking
    there means displacing **that** jump — one whole instruction, so a legal displaced span — and a
    trampoline that replays the displaced bytes verbatim would re-encode nothing and land wherever that
    offset happens to fall from the trampoline. So the jump is relocated to the same absolute destination
    (``build_trampoline``, mirroring ``third_party/minhook/src/trampoline.c:180-209``), and the restore
    writes the five bytes back so the other runtime keeps working.
    """

    #: Where the other runtime's jump goes. Any address will do: the hooker only encodes it, and the
    #: execution test below gives it a real one.
    FOREIGN_DESTINATION = 0x30000000

    @classmethod
    def foreign_jump(cls) -> bytes:
        """Return the five bytes another runtime's entry patch has at ``TARGET``."""

        return bytes((0xE9,)) + struct.pack(
            "<I", (cls.FOREIGN_DESTINATION - (TARGET + 5)) & 0xFFFFFFFF
        )

    def test_a_displaced_jump_is_recognised_by_its_shape(self) -> None:
        """Five bytes and a leading ``E9``; anything else is not this, whatever it contains."""

        self.assertTrue(is_relative_jump(self.foreign_jump()))
        self.assertFalse(is_relative_jump(ORIGINAL), "a prologue is replayed, not relocated")
        self.assertFalse(is_relative_jump(self.foreign_jump() + b"\x90"))
        self.assertFalse(
            is_relative_jump(bytes((0xEB, 0x10))), "a short jump is not five bytes nor an E9"
        )

    def test_the_trampoline_jumps_to_the_same_absolute_destination(self) -> None:
        """The relocated copy reaches where the original reached, from wherever it is put."""

        first = build_trampoline(ALLOC_BASE, self.foreign_jump(), TARGET + 5)
        second = build_trampoline(ALLOC_BASE + 0x1000, self.foreign_jump(), TARGET + 5)

        self.assertEqual(len(first), 5, "an unconditional jump leaves nothing to resume at")
        self.assertEqual(first[0], 0xE9)
        for trampoline, address in ((first, ALLOC_BASE), (second, ALLOC_BASE + 0x1000)):
            destination = (address + 5 + struct.unpack("<i", trampoline[1:5])[0]) & 0xFFFFFFFF
            self.assertEqual(destination, self.FOREIGN_DESTINATION)
        self.assertNotEqual(first, second, "the same target from two addresses is two encodings")

    def test_a_prologue_without_a_jump_is_still_replayed_verbatim(self) -> None:
        """The ordinary case is untouched: the displaced bytes, then a jump back."""

        trampoline = build_trampoline(ALLOC_BASE, ORIGINAL, TARGET + len(ORIGINAL))

        self.assertEqual(trampoline[: len(ORIGINAL)], ORIGINAL)
        self.assertEqual(trampoline[len(ORIGINAL)], 0xE9)

    def test_the_entry_gets_this_projects_patch_and_the_jump_comes_back(self) -> None:
        """The round trip that leaves the other runtime exactly as it was."""

        target = FakeTarget()
        foreign = self.foreign_jump()
        target.write(TARGET, foreign)
        hooker = new_hooker(target)

        hooker.install("entry", TARGET, foreign)

        placed = target.entry()
        self.assertEqual(placed[0], 0xE9)
        self.assertNotEqual(placed[:5], foreign, "this library's own jump is at the entry now")
        stub = sorted(target.allocated)[-1]
        self.assertEqual(
            (TARGET + 5 + struct.unpack("<i", placed[1:5])[0]) & 0xFFFFFFFF,
            stub,
            "and it lands on this library's stub",
        )

        hooker.remove("entry")

        self.assertEqual(
            target.at(TARGET, len(foreign)),
            foreign,
            "the other runtime's jump is back at the entry, byte for byte",
        )
        self.assertEqual(
            target.at(TARGET + len(foreign), 4),
            ORIGINAL[len(foreign) :],
            "and the bytes the patch never covered are untouched",
        )


class RelocatedJumpExecutionTests(unittest.TestCase):
    """The relocated jump is **executed**, because bytes that look right can still land wrong.

    A trampoline holding the foreign entry patch's five bytes verbatim would be a valid-looking jump that
    reaches ``destination - (trampoline_address - entry_address)`` — off by exactly the distance between
    the two buffers, which on a real client is hundreds of megabytes away from anything. This test gives
    the destination a real function and calls the trampoline, so "reaches the same code" is measured
    rather than argued. It needs a 32-bit interpreter, like the rig above: the addresses have to fit the
    four bytes a ``jmp rel32`` encodes.
    """

    MARKER = 0x1234ABCD

    def setUp(self) -> None:
        self.allocations: list[int] = []
        self.addCleanup(self._release_all)

    def _allocate(self, code: bytes) -> int:
        address = kernel32.VirtualAlloc(
            None, 0x1000, MEM_COMMIT_RESERVE, PAGE_EXECUTE_READWRITE
        )
        if not address or address > 0xFFFFFFFF:
            self.skipTest("this test needs the 32-bit interpreter the project is run with")
        ctypes.memmove(address, code, len(code))
        self.allocations.append(int(address))
        return int(address)

    def _release_all(self) -> None:
        for address in self.allocations:
            kernel32.VirtualFree(ctypes.c_void_p(address), 0, MEM_RELEASE)

    def test_the_trampoline_reaches_the_code_the_entry_jump_named(self) -> None:
        """``mov eax, MARKER; ret`` at the destination, reached through the relocated jump."""

        destination = self._allocate(
            struct.pack("<BI", 0xB8, self.MARKER) + b"\xc3"
        )
        entry = destination + 0x200
        foreign = bytes((0xE9,)) + struct.pack(
            "<I", (destination - (entry + 5)) & 0xFFFFFFFF
        )
        trampoline_code = build_trampoline(0, foreign, entry + len(foreign))
        trampoline = self._allocate(trampoline_code)
        # The trampoline's own address is what its jump was encoded against, so it is built once more
        # now that the address is known.
        ctypes.memmove(trampoline, build_trampoline(trampoline, foreign, entry + len(foreign)), 5)

        result = ctypes.CFUNCTYPE(ctypes.c_uint32)(trampoline)()

        self.assertEqual(result, self.MARKER)

    def test_the_verbatim_bytes_would_not_have_reached_it(self) -> None:
        """Which is the whole reason for relocating: the copied jump lands elsewhere."""

        destination = self._allocate(struct.pack("<BI", 0xB8, self.MARKER) + b"\xc3")
        entry = destination + 0x200
        foreign = bytes((0xE9,)) + struct.pack(
            "<I", (destination - (entry + 5)) & 0xFFFFFFFF
        )
        trampoline = self._allocate(foreign + b"\x00")

        reached = (trampoline + 5 + struct.unpack("<i", foreign[1:5])[0]) & 0xFFFFFFFF

        self.assertNotEqual(
            reached, destination, "the copied displacement names a different address entirely"
        )
        self.assertNotEqual(reached, entry)


class ForeignCodeInGeneratedCodeTests(unittest.TestCase):
    """A runtime that hooks *this project's stub*: what the removal does about it.

    Reforged Native hooks the client through MinHook, and ``HookBase::CreateHook`` resolves a target
    through a near branch before hooking it (``base/hooker.cpp:78-80`` follows ``base/scanner.cpp``'s
    ``FunctionFromNearCall``). When this library's entry patch is already at the client function, that
    branch is this library's own ``jmp``, so MinHook places its hook on **this stub** — its own
    five-byte jump at the stub's first byte, and a trampoline that jumps back into the stub past them
    (``third_party/minhook/src/hook.c:355``, ``trampoline.c:281-282``). Both hooks then run on every
    call, which is what was measured live on 2026-10-01.

    What the stub must not do is get freed underneath that: MinHook writes its saved bytes back with a
    blind ``memcpy`` and frees its trampolines wholesale (``hook.c:381-386``, ``buffer.c:74-85``), so
    the stub it patched and its trampoline's return address are both inside this library's allocation.
    The tests below drive exactly that state — a foreign jump written over the stub's head — and check
    that the removal reports it and frees nothing, and that it goes back to freeing normally once the
    foreign patch is gone.
    """

    @staticmethod
    def stub_address(target: FakeTarget) -> int:
        """Return where the hooker put the stub: the allocation that begins with its prologue."""

        for address in sorted(target.allocated):
            if is_generated_stub(target.at(address, len(STUB_PROLOGUE))):
                return address
        raise AssertionError("no allocation begins with the generated stub's prologue")

    def test_the_stub_begins_with_the_prologue_the_projects_own_code_is_recognised_by(self) -> None:
        """``pushfd``, ``pushad``, ``mov eax, imm32`` — both stub forms, one signature."""

        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)

        head = target.at(self.stub_address(target), len(STUB_PROLOGUE))

        self.assertEqual(head, STUB_PROLOGUE)
        self.assertEqual(head, bytes.fromhex("9C 60 B8"))
        self.assertTrue(is_generated_stub(head))
        self.assertFalse(is_generated_stub(bytes.fromhex("E9 00 00 00 00")), "a foreign entry patch")

    def test_a_foreign_patch_inside_the_stub_is_reported_and_nothing_is_freed(self) -> None:
        """The refusal names the stub, restores the entry, and leaves every allocation mapped."""

        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        stub = self.stub_address(target)
        # What MinHook writes there: a five-byte jump to its relay, in its own module.
        foreign = bytes((0xE9,)) + struct.pack("<I", 0x70000000 - (stub + 5))
        target.write(stub, foreign)

        with self.assertRaises(RuntimeError) as caught:
            hooker.remove("entry", free_code=True)

        self.assertIn(f"0x{stub:08X}", str(caught.exception))
        self.assertIn("Nothing was freed", str(caught.exception))
        self.assertIn("Unload the other runtime", str(caught.exception))
        self.assertEqual(target.freed, [], "the stub the foreign patch lives in stays mapped")
        self.assertEqual(target.entry(), ORIGINAL, "and the client's function has its own bytes back")

    def test_the_stub_is_freed_again_once_the_foreign_patch_is_gone(self) -> None:
        """Which is what makes "the other runtime comes out first" a clean teardown and not a leak."""

        target = FakeTarget()
        hooker = new_hooker(target)
        hooker.install("entry", TARGET, ORIGINAL)
        stub = self.stub_address(target)
        head = target.at(stub, STUB_HEAD_SIZE)

        # MinHook's own disable writes its backup — the stub's real head — straight back.
        target.write(stub, bytes((0xE9,)) + struct.pack("<I", 0x70000000 - (stub + 5)))
        target.write(stub, head)

        hooker.remove("entry", free_code=True)

        self.assertEqual(len(target.freed), 2, "nothing is left behind once the stub is ours again")


class _PostCallRig:
    """A synthetic hooked function this process can really call, with the post-call stub on it.

    The function is six bytes of prologue (the entry patch's displaced bytes) then a body that
    writes a marker and returns ``RIG_RESULT``. The rig patches its entry with the real
    :func:`build_entry_patch`, so a test drives the generated code and not a model of it.
    """

    #: What the synthetic function's body returns, and what it writes to the marker.
    RESULT = 0x12345678
    MARKER = 0x1234

    #: ``push ebp``, ``mov ebp, esp``, ``sub esp, 8``: whole instructions, at least five bytes.
    DISPLACED = bytes.fromhex("558BEC83EC08")

    def __init__(self) -> None:
        self.allocations: list[int] = []
        self.marker = ctypes.c_uint32(0)
        body = (
            bytes.fromhex("C705")
            + struct.pack("<I", ctypes.addressof(self.marker))
            + struct.pack("<I", self.MARKER)
            + bytes.fromhex("B878563412C9C3")  # mov eax, RIG_RESULT / leave / ret
        )
        self.target = self._allocate(self.DISPLACED + body)
        self.trampoline = self._allocate(b"")
        self._write(
            self.trampoline,
            build_trampoline(
                self.trampoline, self.DISPLACED, self.target + len(self.DISPLACED)
            ),
        )
        self.state = self._allocate(bytes(post_state_size(FORWARDED)))
        ctypes.memset(self.state, 0, post_state_size(FORWARDED))
        self.set_enabled(1)
        self.stub = self._allocate(b"")
        self.set_payload(None)
        ctypes.memmove(
            self.target,
            build_entry_patch(self.target, self.stub, len(self.DISPLACED)),
            len(self.DISPLACED),
        )
        # ``__cdecl``: the body ends in a plain ``ret``, so the caller cleans the arguments.
        self.call = ctypes.CFUNCTYPE(
            ctypes.c_uint32, ctypes.c_uint32, ctypes.c_uint32
        )(self.target)
        self.snippet = ctypes.CFUNCTYPE(ctypes.c_uint32)(
            self._allocate(bytes.fromhex("8BC4C3"))  # mov eax, esp / ret
        )

    def _allocate(self, code: bytes) -> int:
        address = kernel32.VirtualAlloc(
            None, len(code) + 64, MEM_COMMIT_RESERVE, PAGE_EXECUTE_READWRITE
        )
        if not address:
            raise OSError(ctypes.get_last_error(), "VirtualAlloc failed.")
        self.allocations.append(int(address))
        if code:
            self._write(int(address), code)
        return int(address)

    @staticmethod
    def _write(address: int, code: bytes) -> None:
        ctypes.memmove(address, code, len(code))

    def set_payload(self, function: object) -> None:
        """Place ``function`` as the payload, and rebuild the stub over it at the same address.

        The ``ctypes`` callback is kept on the rig: it owns a small thunk, and letting it be
        collected would free the address the stub calls.
        """

        self.payload = (
            None if function is None else self.payload_type()(function)
        )
        address = (
            0
            if self.payload is None
            else (ctypes.cast(self.payload, ctypes.c_void_p).value or 0)
        )
        code = build_stub(
            stub_address=self.stub,
            state_address=self.state,
            block_address=RIG_BLOCK,
            dispatcher_address=address,
            trampoline_address=self.trampoline,
            forwarded_arguments=FORWARDED,
            post_payload=True,
        )
        self._write(self.stub, code)

    def payload_type(self) -> type:
        """Return the ``__stdcall`` signature a forwarding payload is called with."""

        return ctypes.WINFUNCTYPE(
            None, ctypes.c_void_p, ctypes.c_uint32, ctypes.c_void_p
        )

    def stack_pointer(self) -> int:
        """Return esp, measured rather than inferred: a drift shows up as a difference."""

        return int(self.snippet())

    def depth(self) -> int:
        return int(ctypes.c_uint32.from_address(self.state + POST_DEPTH_OFFSET).value)

    def in_flight(self) -> int:
        """Return the stub's own in-flight count, read from the state the stub writes."""

        return int(
            ctypes.c_uint32.from_address(self.state + STATE_INFLIGHT_OFFSET).value
        )

    def set_depth(self, value: int) -> None:
        ctypes.c_uint32.from_address(self.state + POST_DEPTH_OFFSET).value = value

    def set_enabled(self, value: int) -> None:
        ctypes.c_uint32.from_address(self.state).value = value

    def marker_value(self) -> int:
        return int(self.marker.value)

    def close(self) -> None:
        for address in self.allocations:
            kernel32.VirtualFree(address, 0, MEM_RELEASE)
        self.allocations = []


class PostCallExecutionTests(unittest.TestCase):
    """The post-call stub, executed: what the payload sees and what the caller gets back."""

    def setUp(self) -> None:
        self.rig = _PostCallRig()
        self.addCleanup(self.rig.close)

    def test_the_payload_runs_after_the_body_and_sees_the_arguments(self) -> None:
        """The whole point of the form: the label is only the client's string inside the call."""

        seen: list[tuple[int, int, int, int]] = []

        def payload(block: int, first: int, second: int) -> None:
            seen.append(
                (int(block), int(first), int(second), self.rig.marker_value())
            )

        self.rig.set_payload(payload)
        result = self.rig.call(0xAAAA, 0xBBBB)

        self.assertEqual(result, _PostCallRig.RESULT, "the caller keeps the body's value")
        self.assertEqual(len(seen), 1, "the payload runs exactly once per call")
        block, first, second, marker = seen[0]
        self.assertEqual(block, RIG_BLOCK)
        self.assertEqual(first, 0xAAAA, "the first argument is the one the call was made with")
        self.assertEqual(second, 0xBBBB, "and so is the second")
        self.assertEqual(marker, _PostCallRig.MARKER, "the body had already run")

    def test_the_stack_is_where_the_call_left_it(self) -> None:
        seen: list[int] = []
        self.rig.set_payload(lambda block, first, second: seen.append(1))

        before = self.rig.stack_pointer()
        self.rig.call(0x1111, 0x2222)
        after = self.rig.stack_pointer()

        self.assertEqual(len(seen), 1)
        self.assertEqual(before, after, "a byte of drift here is a crash later")

    def test_the_frame_is_released_after_each_call(self) -> None:
        self.rig.set_payload(lambda block, first, second: None)

        for _ in range(3):
            self.rig.call(0x1, 0x2)

        self.assertEqual(self.rig.depth(), 0, "every level is given back")

    def test_a_payload_that_sends_the_message_again_nests(self) -> None:
        """A client can send a message while handling one, and each level keeps its own frame."""

        results: list[int] = []
        markers: list[int] = []

        def payload(block: int, first: int, second: int) -> None:
            markers.append(self.rig.marker_value())
            if len(markers) == 1:
                results.append(self.rig.call(0x3333, 0x4444))

        self.rig.set_payload(payload)
        before = self.rig.stack_pointer()
        outer = self.rig.call(0x5555, 0x6666)
        after = self.rig.stack_pointer()

        self.assertEqual(len(markers), 2, "the nested call runs the payload too")
        self.assertEqual(results, [_PostCallRig.RESULT], "the nested call returns normally")
        self.assertEqual(outer, _PostCallRig.RESULT, "and so does the outer one")
        self.assertEqual(before, after)
        self.assertEqual(self.rig.depth(), 0)

    def test_a_full_frame_stack_passes_the_call_through(self) -> None:
        """No level left: the event is dropped rather than the client asked to wait."""

        seen: list[int] = []
        self.rig.set_payload(lambda block, first, second: seen.append(1))
        self.rig.set_depth(POST_DEPTH)

        before = self.rig.stack_pointer()
        result = self.rig.call(0x7777, 0x8888)
        after = self.rig.stack_pointer()

        self.assertEqual(result, _PostCallRig.RESULT)
        self.assertEqual(seen, [], "no frame means no payload")
        self.assertEqual(before, after)
        self.assertEqual(self.rig.depth(), POST_DEPTH, "a call that is not taken changes nothing")

    def test_a_disabled_hook_passes_the_call_through(self) -> None:
        seen: list[int] = []
        self.rig.set_payload(lambda block, first, second: seen.append(1))
        self.rig.set_enabled(0)

        before = self.rig.stack_pointer()
        result = self.rig.call(0x9999, 0xAAAA)
        after = self.rig.stack_pointer()

        self.assertEqual(result, _PostCallRig.RESULT)
        self.assertEqual(seen, [])
        self.assertEqual(before, after)


if __name__ == "__main__":
    unittest.main(verbosity=2)
