"""Guild Wars context readers and external array views."""

from . import char_context
from . import cinematic_context
from . import game_context
from . import gameplay_context
from . import pre_game_context
from . import server_region_context
from . import player_agent_id_context
from . import instance_info_context
from . import text_parser_context
from . import available_character_context
from . import party_context
from . import guild_context
from . import acc_agent_context
from . import agent_array
from . import camera_context
from . import friend_list_context
from . import chat_buffer_context
from . import world_context
from . import trade_context
from . import item_context
from . import account_context
from . import gadget_context
from . import render_context
from . import mission_map_context
from . import world_map_context
from . import salvage_context
from .char_context import (
    CharContext,
    CharContextStruct,
    ObserverMatch,
    ObserverMatchFlags,
    ProgressBar,
    get,
)
from .cinematic_context import Cinematic, CinematicStruct
from .game_context import GameContext, GameContextStruct
from .map_context import (
    BlockingPropStruct,
    MapPropStruct,
    MapContext,
    MapContextStruct,
    MapStaticDataStruct,
    MapVec2fStruct,
    MapVec3fStruct,
    NativeMapPropStruct,
    NodeStruct,
    NativePathingMapStruct,
    NativePathingTrapezoidStruct,
    NativePortalStruct,
    NativePropsContextStruct,
    NativeSinkNodeStruct,
    NativeXNodeStruct,
    NativeYNodeStruct,
    NativeMapContextPrefixStruct,
    NativeMapContextSub1Struct,
    NativeMapContextSub2Struct,
    Node,
    PathingTrapezoidStruct,
    PathingTrapezoid,
    PathContextStruct,
    PathingMap,
    PathingMapStruct,
    Portal,
    PortalStruct,
    PropByTypeStruct,
    PropModelInfoStruct,
    PropsContextStruct,
    RecObjectStruct,
    SinkNodeStruct,
    SinkNode,
    SpawnEntryStruct,
    SpawnPoint,
    TravelPortal,
    XNode,
    YNode,
    XNodeStruct,
    YNodeStruct,
)
from .gameplay_context import GameplayContext, GameplayContextStruct
from .pre_game_context import (
    LoginCharacter,
    PreGameContext,
    PreGameContextStruct,
)
from .server_region_context import ServerRegion, ServerRegionStruct
from .player_agent_id_context import (
    PlayerAgentId,
    PlayerAgentIdStruct,
)
from .instance_info_context import (
    AreaInfoStruct,
    InstanceInfo,
    InstanceInfoStruct,
    InstanceType,
    MapDimensionsStruct,
)
from .text_parser_context import (
    LanguageSlotStruct,
    TextCacheStruct,
    TextFileSlotStruct,
    TextParser,
    TextParserStruct,
    TextParserSubStructStruct,
)
from .available_character_context import (
    AvailableCharacterArray,
    AvailableCharacterArrayStruct,
    AvailableCharacterInfoStruct,
    AvailableCharacterStruct,
)
from .party_context import (
    HenchmanPartyMember,
    HenchmanPartyMemberStruct,
    HeroPartyMember,
    HeroPartyMemberStruct,
    PartyContext,
    PartyContextStruct,
    PartyInfoStruct,
    PartySearchStruct,
    PartySearchType,
    PlayerPartyMember,
    PlayerPartyMemberStruct,
)
from .guild_context import (
    CapeDesign,
    CapeDesignStruct,
    GHKey,
    GHKeyStruct,
    Guild,
    GuildContext,
    GuildContextStruct,
    GetGuildArray,
    GuildHistoryEvent,
    GuildHistoryEventStruct,
    GuildPlayer,
    GuildPlayerStruct,
    GuildStruct,
    TownAlliance,
    TownAllianceStruct,
)
from .acc_agent_context import (
    AccAgentContext,
    AccAgentContextStruct,
    AgentInfo,
    AgentInfoArray,
    AgentInfoStruct,
    AgentContext,
    AgentContextStruct,
    AgentMovement,
    AgentMovementStruct,
    AgentSummaryInfo,
    AgentSummaryInfoStruct,
    AgentSummaryInfoSub,
    AgentSummaryInfoSubStruct,
    Vec3f,
    Vec3fStruct,
)
from .agent_array import (
    AgentAllegiance,
    AgentArray,
    AgentArrayStruct,
    AgentArraySnapshot,
    AgentGadget,
    AgentGadgetStruct,
    AgentItem,
    AgentItemStruct,
    AgentLiving,
    AgentLivingStruct,
    AgentKind,
    AgentNative,
    AgentStruct,
    AgentReference,
    AgentType,
    DyeInfo,
    Equipment,
    EquipmentItemIDsUnion,
    EquipmentItemsUnion,
    ItemData,
    LivingAgentSnapshot,
    ReforgedAgentLivingStruct,
    ReforgedEquipmentItemsUnionStruct,
    ReforgedEquipmentStruct,
    ReforgedItemDataStruct,
    StaleAgentReferenceError,
    TagInfo,
    VisibleEffect,
    VisibleEffectStruct,
    DyeInfoStruct,
    ItemDataStruct,
    EquipmentStruct,
    TagInfoStruct,
)
from .camera_context import Camera, CameraStruct
from .friend_list_context import (
    FriendList,
    FriendListStruct,
    FriendEventDataStruct,
    FriendStruct,
    FriendStatus,
    FriendType,
)
from .chat_buffer_context import (
    ChatBuffer,
    ChatBufferStruct,
    ChatMessageStruct,
    FileTimeStruct,
)
from .world_context import (
    AgentEffectsStruct,
    AccountInfoStruct,
    AttributeStruct,
    BuffStruct,
    ControlledMinionsStruct,
    EffectStruct,
    AgentNameInfoStruct,
    NPCStruct,
    NPC_ModelStruct,
    PartyAttributeStruct,
    PartyAllyStruct,
    PartyMemberMoraleInfoStruct,
    PartyMoraleLinkStruct,
    HeroFlagStruct,
    HeroInfoStruct,
    MapAgentStruct,
    MissionMapIconStruct,
    PetInfoStruct,
    PlayerStruct,
    PlayerControlledCharacterStruct,
    ProfessionStateStruct,
    SkillbarSkillStruct,
    SkillbarCastStruct,
    SkillbarStruct,
    DupeSkillStruct,
    GamePos as WorldGamePos,
    GamePosStruct,
    MissionObjectiveStruct,
    QuestStruct,
    TitleStruct,
    TitleTierStruct,
    Vec3fStruct as WorldVec3fStruct,
    Vec2fStruct as WorldVec2fStruct,
    Vec3f as WorldVec3f,
    Vec2f as WorldVec2f,
    WorldContext,
    WorldContextStruct,
)
from .trade_context import (
    TradeContext,
    TradeContextStruct,
    TradeItemStruct,
    TradePlayerStruct,
)
from .item_context import (
    BagStruct,
    DyeInfoStruct,
    InventoryTableEntryStruct,
    InventoryStruct,
    ItemClickParamStruct,
    ItemModifierStruct,
    MaterialCostStruct,
    ItemRarity,
    ItemContext,
    ItemContextStruct,
    ItemFormulaStruct,
    PvPItemInfoStruct,
    PvPItemUpgradeInfoStruct,
    CompositeModelInfoStruct,
    SalvageSessionInfoStruct,
    ItemStruct,
    WeaponSetStruct,
)
from .account_context import (
    AccountContext,
    AccountContextStruct,
    AccountUnlockedCountStruct,
    AccountUnlockedItemInfoStruct,
)
from .gadget_context import GadgetContext, GadgetContextStruct, GadgetInfoStruct
from .render_context import GwDxContextStruct
from .salvage_context import (
    SalvageSessionInfo,
    SalvageSessionInfoRecord,
    SalvageSessionInfoStruct,
)
from .mission_map_context import (
    MissionMapContext,
    MissionMapContextStruct,
    MissionMapSubContext,
    MissionMapSubContext2,
)
from .world_map_context import WorldMapContext, WorldMapContextStruct
from .gw_array import (
    GW_Array,
    GW_Array_Value_View,
    GW_Array_View,
    GW_BaseArray,
    GWArray,
    GWArrayValueView,
    GWArrayView,
    GWBaseArray,
)
from .gw_list import GWLinkStruct, GWListStruct, RemoteGWListView

__all__ = [
    "CharContext",
    "CharContextStruct",
    "Cinematic",
    "CinematicStruct",
    "GameContext",
    "GameContextStruct",
    "MapContext",
    "MapContextStruct",
    "MapPropStruct",
    "MapStaticDataStruct",
    "MapVec2fStruct",
    "MapVec3fStruct",
    "PathingMap",
    "PathingTrapezoid",
    "Portal",
    "SinkNode",
    "TravelPortal",
    "Node",
    "XNode",
    "YNode",
    "NodeStruct",
    "NativeMapContextPrefixStruct",
    "NativeMapContextSub1Struct",
    "NativeMapContextSub2Struct",
    "PathingTrapezoidStruct",
    "PathContextStruct",
    "PathingMapStruct",
    "PortalStruct",
    "PropByTypeStruct",
    "PropModelInfoStruct",
    "PropsContextStruct",
    "RecObjectStruct",
    "SinkNodeStruct",
    "SpawnEntryStruct",
    "SpawnPoint",
    "BlockingPropStruct",
    "XNodeStruct",
    "YNodeStruct",
    "GameplayContext",
    "GameplayContextStruct",
    "ServerRegion",
    "ServerRegionStruct",
    "PlayerAgentId",
    "PlayerAgentIdStruct",
    "InstanceInfo",
    "InstanceInfoStruct",
    "InstanceType",
    "MapDimensionsStruct",
    "AreaInfoStruct",
    "TextParser",
    "TextParserStruct",
    "TextCacheStruct",
    "TextFileSlotStruct",
    "LanguageSlotStruct",
    "TextParserSubStructStruct",
    "AvailableCharacterArray",
    "AvailableCharacterArrayStruct",
    "AvailableCharacterInfoStruct",
    "AvailableCharacterStruct",
    "PartyContext",
    "PartyContextStruct",
    "PartyInfoStruct",
    "PartySearchStruct",
    "PartySearchType",
    "PlayerPartyMemberStruct",
    "PlayerPartyMember",
    "HeroPartyMemberStruct",
    "HeroPartyMember",
    "HenchmanPartyMemberStruct",
    "HenchmanPartyMember",
    "PreGameContext",
    "PreGameContextStruct",
    "LoginCharacter",
    "ObserverMatch",
    "ObserverMatchFlags",
    "ProgressBar",
    "GWArray",
    "GWBaseArray",
    "GWArrayView",
    "GWArrayValueView",
    "GW_Array",
    "GW_BaseArray",
    "GW_Array_View",
    "GW_Array_Value_View",
    "GWLinkStruct",
    "GWListStruct",
    "RemoteGWListView",
    "GuildContext",
    "GuildContextStruct",
    "GetGuildArray",
    "GHKeyStruct",
    "CapeDesignStruct",
    "TownAllianceStruct",
    "GuildHistoryEventStruct",
    "GuildStruct",
    "GuildPlayerStruct",
    "GHKey",
    "CapeDesign",
    "TownAlliance",
    "GuildHistoryEvent",
    "Guild",
    "GuildPlayer",
    "AccAgentContext",
    "AccAgentContextStruct",
    "AgentInfo",
    "AgentInfoArray",
    "AgentInfoStruct",
    "AgentContext",
    "AgentContextStruct",
    "AgentMovementStruct",
    "AgentSummaryInfoStruct",
    "AgentSummaryInfoSubStruct",
    "Vec3fStruct",
    "Vec3f",
    "AgentSummaryInfoSub",
    "AgentSummaryInfo",
    "AgentMovement",
    "AgentArray",
    "AgentArrayStruct",
    "AgentArraySnapshot",
    "AgentStruct",
    "AgentNative",
    "AgentLiving",
    "AgentLivingStruct",
    "AgentItem",
    "AgentItemStruct",
    "AgentGadget",
    "AgentGadgetStruct",
    "AgentKind",
    "AgentAllegiance",
    "AgentReference",
    "AgentType",
    "LivingAgentSnapshot",
    "ReforgedAgentLivingStruct",
    "StaleAgentReferenceError",
    "VisibleEffectStruct",
    "VisibleEffect",
    "DyeInfoStruct",
    "DyeInfo",
    "ItemDataStruct",
    "ReforgedItemDataStruct",
    "ItemData",
    "ReforgedEquipmentItemsUnionStruct",
    "EquipmentStruct",
    "ReforgedEquipmentStruct",
    "Equipment",
    "EquipmentItemsUnion",
    "EquipmentItemIDsUnion",
    "TagInfoStruct",
    "TagInfo",
    "Camera",
    "CameraStruct",
    "FriendList",
    "FriendListStruct",
    "FriendEventDataStruct",
    "FriendStruct",
    "FriendStatus",
    "FriendType",
    "ChatBuffer",
    "ChatBufferStruct",
    "ChatMessageStruct",
    "FileTimeStruct",
    "WorldContext",
    "WorldContextStruct",
    "WorldVec3fStruct",
    "WorldVec2fStruct",
    "WorldGamePos",
    "WorldVec3f",
    "WorldVec2f",
    "AccountInfoStruct",
    "MapAgentStruct",
    "PartyAllyStruct",
    "ControlledMinionsStruct",
    "PartyMemberMoraleInfoStruct",
    "PartyMoraleLinkStruct",
    "PlayerControlledCharacterStruct",
    "ProfessionStateStruct",
    "SkillbarCastStruct",
    "AgentNameInfoStruct",
    "MissionMapIconStruct",
    "AttributeStruct",
    "PartyAttributeStruct",
    "EffectStruct",
    "BuffStruct",
    "AgentEffectsStruct",
    "NPCStruct",
    "NPC_ModelStruct",
    "HeroFlagStruct",
    "HeroInfoStruct",
    "PetInfoStruct",
    "PlayerStruct",
    "SkillbarSkillStruct",
    "SkillbarStruct",
    "DupeSkillStruct",
    "GamePosStruct",
    "QuestStruct",
    "MissionObjectiveStruct",
    "TitleStruct",
    "TitleTierStruct",
    "TradeContext",
    "TradeContextStruct",
    "TradeItemStruct",
    "TradePlayerStruct",
    "ItemContext",
    "ItemContextStruct",
    "ItemFormulaStruct",
    "MaterialCostStruct",
    "WeaponSetStruct",
    "SalvageSessionInfoStruct",
    "ItemClickParamStruct",
    "InventoryTableEntryStruct",
    "PvPItemInfoStruct",
    "PvPItemUpgradeInfoStruct",
    "CompositeModelInfoStruct",
    "DyeInfoStruct",
    "ItemModifierStruct",
    "ItemRarity",
    "ItemStruct",
    "BagStruct",
    "InventoryStruct",
    "AccountContext",
    "AccountContextStruct",
    "AccountUnlockedCountStruct",
    "AccountUnlockedItemInfoStruct",
    "GadgetContext",
    "GadgetContextStruct",
    "GadgetInfoStruct",
    "GwDxContextStruct",
    "MissionMapContext",
    "MissionMapContextStruct",
    "MissionMapSubContext",
    "MissionMapSubContext2",
    "SalvageSessionInfo",
    "SalvageSessionInfoRecord",
    "SalvageSessionInfoStruct",
    "WorldMapContext",
    "WorldMapContextStruct",
    "char_context",
    "cinematic_context",
    "game_context",
    "gameplay_context",
    "pre_game_context",
    "server_region_context",
    "instance_info_context",
    "text_parser_context",
    "available_character_context",
    "party_context",
    "guild_context",
    "acc_agent_context",
    "agent_array",
    "camera_context",
    "friend_list_context",
    "chat_buffer_context",
    "world_context",
    "trade_context",
    "item_context",
    "account_context",
    "gadget_context",
    "render_context",
    "salvage_context",
    "charcontext",
    "cinematic",
    "gamecontext",
    "gameplaycontext",
    "pregamecontext",
    "serverregion",
    "instanceinfo",
    "textparser",
    "availablecharacters",
    "partycontext",
    "guildcontext",
    "accagentcontext",
    "camera",
    "friendlist",
    "chatbuffer",
    "worldcontext",
    "tradecontext",
    "itemcontext",
    "accountcontext",
    "gadgetcontext",
    "mapcontext",
    "missionmapcontext",
    "worldmapcontext",
    "salvagecontext",
    "cameracontext",
    "get",
]

# Keep the short facade spelling while using one implementation file.
charcontext = char_context
cinematic = cinematic_context
gamecontext = game_context
gameplaycontext = gameplay_context
pregamecontext = pre_game_context
serverregion = server_region_context
playeragentid = player_agent_id_context
instanceinfo = instance_info_context
textparser = text_parser_context
availablecharacters = available_character_context
partycontext = party_context
guildcontext = guild_context
accagentcontext = acc_agent_context
camera = camera_context
friendlist = friend_list_context
chatbuffer = chat_buffer_context
worldcontext = world_context
tradecontext = trade_context
itemcontext = item_context
accountcontext = account_context
gadgetcontext = gadget_context
mapcontext = map_context
missionmapcontext = mission_map_context
worldmapcontext = world_map_context
salvagecontext = salvage_context
cameracontext = camera_context
